name:                test
version:             0.1.0.0
license:             MIT
author:              "Konstantin Chugalinskiy"
maintainer:          "kchugalinskiy@yandex.ru"

description:         Dummy web server

dependencies:
- base >= 4.7 && < 5

executables:
  test-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - wai
    - warp
    - http-types
    - blaze-builder
    - utf8-string
    