flags: {}
packages:
- .
extra-deps: []
resolver: lts-10.3

image:
  containers:
    -
      base: "fpco/ubuntu-with-libgmp:14.04"
      name: "hello-world"
      entrypoints:
        - test-exe
        